---
# tasks file for builder
- name: Ensure package is present
  apt: name=git state=present
  apt: name=jdk state=present
  apt: name=maven state=present
- name: create directory
  file:
    path: /home/{{project}}
    state: directory
- name: clone repository
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: /home/{{project}}
- name: build package
  shell: mvn package
  args:
    chdir: /home/{{project}}
