---
# tasks file for builder
- name: Ensure package is present
  apt: name={{item}} state=present
  with_items:
    - git
    - default-jdk
    - maven
    - docker.io
- name: create directory
  file: path=/home/{{project}} state=directory
- name: clone repository
  git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/{{project}}
- name: build package
  shell: mvn package
  args:
    chdir: /home/{{project}}
- name: copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/Dockerfile
- name: build container image
  docker_image:
    name: mytomcat:latest
    build:
      path: /home
    source: build
- name: Create a data container
  docker_container:
    name: tomcat
    image: mytomcat
- name: Copy build to container
  shell: docker cp /home/boxfuse/target/hello-1.0.war tomcat:/opt/tomcat/webapps/hello-1.0.war
- name: Log into DockerHub
  docker_login:
    username: dmitrydok
    password: DoktOrD1
    email: doktord1@yandex.ru
- name: Tag and push to docker hub
  docker_image:
    name: tomcat
    repository: dmitrydok/tomcat
    tag: latest
    push: yes
- name: Log out of DockerHub
  docker_login:
    state: absent
    email: doktord1@yandex.ru